create table if not exists device_logs (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null default now(),
  level text not null,
  message text not null,
  device_id text,
  -- optional foreign key to a devices table if exists
  -- foreign key (device_id) references devices(id) on delete set null
);
